### ISSUE TITLE
Silently swallowed error

### ISSUE THREAD

**Issue by agentydragon** [infinytum/reactive#3]
https://github.com/infinytum/reactive/blob/c12d8413dd3d7e266111a1bdad36c396f4385c42/take.go

Silently swallows errors and prints to console instead of passing or panicing.

**Comment by nilathedragon** [comment]
The chance of the error happening is 0%

An error occurs only when the passed argument to Subscribe isnt a function. Which in the case of a pipe is never the case. I will add a panic call instead of a print
